### ISSUE TITLE
model  no attribute 'global_variables'

### ISSUE THREAD

**Issue by chenzomi12** [dennybritz/cnn-text-classification-tf#54]
After I run the python train.py, these is an error and I could not solve it. Can anyone know how?

```
Parameters:
ALLOW_SOFT_PLACEMENT=True
BATCH_SIZE=64
CHECKPOINT_EVERY=100
DEV_SAMPLE_PERCENTAGE=0.1
DROPOUT_KEEP_PROB=0.5
EMBEDDING_DIM=128
EVALUATE_EVERY=100
FILTER_SIZES=3,4,5
L2_REG_LAMBDA=0.0
LOG_DEVICE_PLACEMENT=False
NEGATIVE_DATA_FILE=./data/rt-polaritydata/rt-polarity.neg
NUM_EPOCHS=200
NUM_FILTERS=128
POSITIVE_DATA_FILE=./data/rt-polaritydata/rt-polarity.pos

Loading data...
Vocabulary Size: 18758
Train/Dev split: 9596/1066
Writing to /Users/zomi/Downloads/cnn-text-classification-tf-master/runs/1481718705

Traceback (most recent call last):
  File "./train.py", line 129, in <module>
    saver = tf.train.Saver(tf.global_variables())
AttributeError: 'module' object has no attribute 'global_variables'
```

**Comment by dennybritz** [comment]
Wrong TF version.

**Comment by chenzomi12** [comment]
I used the tensorflow 0.11, so which do you recommend?

**Comment by mdymczyk** [comment]
@chenzomi12 0.12 should be fine

**Comment by 9bow** [comment]
...or tying older revision like (c008eba)
it works on tensorflow 0.10
